### ISSUE TITLE
Update to Angular 2+

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/phoenicis-backend#26]
The website currently uses Angular 1 (also called angularjs) for its frontend.
The support for Angular 1 will end in [June 30, 2021](https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c?gi=e81fb72ac52f).
I think it is a good idea to update the website frontend to a different (newer) technology before the support ends.
The most natural choice in my opinion is Angular 2+ (with the current release being version 7).
If we decide to update to Angular 2+, I can help rewrite the frontend code to Angular 2+.

What do you think?

**Comment by plata** [comment]
I'm not really familiar with web technology so I can't judge what's the best framework for us. In general I would agree to go for a future prove technology before investing a lot of time in development which must be reworked again later on.

**Comment by qparis** [comment]
Agreed. By rethinking about it, I'm not really fan of front ends technologies like that for presentation website. 
Also, I think it would be reasonable to keep the community we have on the current website. Therefore, I'm thinking about doing pretty much the same thing between playonlinux.com / playonmac.com with phoenicis.org

The next step for me would be to clean up the current website code (which I am currently doing, but it takes a lot of time) and then release it on github

**Comment by plata** [comment]
Not quite sure I understand you correctly. Do you want to have 2 websites for Phoenicis as well? Apart from that the old website looks a bit outdated really. Also, how does it behave on mobile?

**Comment by qparis** [comment]
No, I was more thinking about not throwing away PlayOnLinux.com. The website has a lot a visit and a large community. In my opinion, it would be a mistake to let it rot.

Also, I think that platform like github won’t be enough to animate a real community 

This is why I’m wondering if we could imagine the following plan:
 - cleaning playonlinux.com, and make it responsible. Some work have been done last week end
 - remove remaining unnecessary feature from pol.com (the bug tracker have been removed, we should continue to track on uneeded stuff)
- create a new design
- make the code open source 
- make phoenicis.org, playonlinux.com and playonmac.com pointing to the same website but contextualized (Phoenicis.org will probably share the forum, but not the list of supported apps)

This has to be done before the release of POLv5, so that we can follow the adoption of the new version

**Comment by qparis** [comment]
This is what we’ve done when playonmac was released years after POL, and it worked pretty well

**Comment by plata** [comment]
My problem with this is: We will have some time where PoL/PoM4 and Phoenicis coexist. It might be confusing to have both on the same website because they are quite different.

**Comment by madoar** [comment]
Using which languages will the "new" website be written?
I mean the current one (phoenicis.org) uses java and angularjs (javascript), which ones will the new one use?

**Comment by qparis** [comment]
@plata There are two ways / philosophies of doing things, each of them have their pros and their cons. 

Either we decide that phoenicis and POL/POM are totally different and unrelated project or we decide that phoenicis should be really considered the next version of POL. 

Advantages of the first way
 - We are free to build everything from scratch and start from a clean codebase. We don't have to bother to manage backward compatibility between old a new ressources (I'm not just talking about the software, but also about change management, winebuilds compatibility, etc...)

Advantage of the second way 
 - We have plenty of users and I expect the adoption rate to be quicker. 

Franky, I'm not a big fan about abandoning a community or imposing a big bang migration, so I prefer the second way. I find it more agile. However, I also perfectly understand that you feel less concerned about this problematic. What do you think?

**Comment by plata** [comment]
I fully agree that we should not abandon the existing community. I'm only wondering if it will not lead to confusion if someone looking for information regarding PoL4 finds himself on a website which is filled with screenshots of Phoenicis etc. I this could be avoided when we have only one website.

**Comment by qparis** [comment]
Maybe we can discuss this problem feature per feature. 
- Home page: easy to solve 
- Download page: also very easy to solve
- Documentation: Maybe we can somehow split the wiki into two parts. That should not be too hard.

The real question is the forum: do we want to have two different forums (more like scenario 1) or only one forum (more like scenario 2). Because this is the key. 

If the first scenario, we install something clean and create a whole new forum like discord on a whole new website 
In the second scenario, we create a phoenicis section on the forum, and we take time to investigate about how to migrate the data later.

**Comment by qparis** [comment]
Also, I find that it is quite rude to impose phoenicis who want to keep POL 4 at the same time to register to two differents websites. We should at least provide minimal support for legacy

**Comment by plata** [comment]
Regarding home page and download page: how would you solve it? Simply a different page for Phoenicis and PoL4? If so, wouldn't this be pretty much the same as 2 websites?

I think we should go for 1 forum with a new section. Here I completely agree that we shouldn't require people to get another account for Phoenicis.

**Comment by qparis** [comment]
Look at http://www.playonlinux.com and http://www.playonmac.com. This is pretty much the same problem that was solved few years ago

**Comment by qparis** [comment]
Again, I fully agree that the site is very old, the code is not clean at all but this is not our "core business"

**Comment by plata** [comment]
Ok. I'm fine with that approach.

Just one question: Do you want to have different pages for Phoenicis PoL and PoM? I think I would prefer something like https://www.jetbrains.com/idea/download/#section=linux.
Actually... Looking at that site: We could do pretty much the same. Just instead of "Tools" (IntelliJ, PyCharm...) we would have PoL/PoM 4 and Phoenicis.

**Comment by qparis** [comment]
Quite agreed with that. Home & Download page are our next priorities

**Comment by plata** [comment]
So back to topic: What about technology. How is the current website built?

**Comment by qparis** [comment]
It is a simple PHP website with a MySQL database... 

So the plan is to build webservices layer between the view and the database (Probably java)

**Comment by qparis** [comment]
Home & download pages are static

**Comment by plata** [comment]
Sounds reasonable to me. Will you create a new repository or reuse the existing one for the website?

**Comment by qparis** [comment]
First of all, I need to clean some stuff (This website was my first "big" project). I think I will release the new site feature by feature on github. Then, it does not really matter on which repository it will be :)

**Comment by plata** [comment]
Ok. Just be sure to do it in a way that people can participate ;)

**Comment by qparis** [comment]
That's the goal. Basically the method is the same than winebuild. I need to extract a part of the code that people can work on, I release it and I connect it to the rest of the ecosystem

**Comment by plata** [comment]
@madoar I think we can close this issue now?

**Comment by madoar** [comment]
Yes
