### ISSUE TITLE
Cookies needed?

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/phoenicis-backend#29]
I understand that cookies are required such that you do not have to enter the login data over and over again. However, this should be sufficient in the forum. All pages containing only information (home, supported software...) should work without that. I find these cookie warning you find all over the web really annoying.

**Comment by qparis** [comment]
Unfortunately, this is impossible for many reasons: 
* The session exists on all the website. This allows for example users with extra privileges to post / comment on news, to intereact on the app section, etc... 
* The browser will send the cookie on the whole domain anyway. Isolating the forum from the rest would be really painful 
* We are also collecting data (analytics, ads, ...) and the law asks us to be transparent with the end user

**Comment by plata** [comment]
Too bad.

**Comment by plata** [comment]
I just saw that the wiki seems to be a separate website as well. Can't we do the same for the forums?

**Comment by qparis** [comment]
Not really, this causes many drawback: 
- need to login twice (website + wiki)
- accounts are not synchronized 

Also, the account system is a core feature of the website, pretty much all the pages are contextualized

**Comment by plata** [comment]
How does this context show? To be honest, I always had the impression that the website only presents dumb information and the login is only used for the forums. Actually, I never log in unless I want to use the forums. I wonder if anybody handles this differently.

**Comment by qparis** [comment]
Some feature are disabled for the moment due to massive spamming, but:
- news comment
- private messages 
- script contribution
- website administration
- later: wine build patch demand
- later: forum notification 

In fact, you are challenging the approach we are using in the website. The idea at the time was to build a complete and unified website where users are always logged in. It means that the developer can add feature for people logged in at any place without wondering if it is possible. I think this is really cool because it will not restrain our ideas.

In any case we will have cookies problem like on any EU based website now
